### ISSUE TITLE
TODO: add this SQL

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-starter-guild#4]
Probably add this in `sql/characters/testing/guild.sql` or `sql/characters/development/guild.sql`

```SQL
-- DEFAULT DATA FOR EASY TESTING/DEVELOPMENT
SET @GUILD_ID := 1; -- Default guild ID
SET @GUILD_NAME := 'TEST';
SET @CHARACTER_ID := 1; -- Character ID that will be the leader of the guild

INSERT INTO `guild` (`guildid`, `name`, `leaderguid`, `motd`) VALUES
(@GUILD_ID, @GUILD_NAME, @CHARACTER_ID, 'Module starter guild works fine!');

-- DELETE GUILD AFTER TESTING IF YOU WANT
-- DELETE FROM `guild` WHERE `guildid` = @GUILD_ID;
```

Also add a line about this SQL file in the README.md

**Comment by pangolp** [comment]
This SQL could be added, but the problem would be if the brotherhoods already exist within the table. That is, the person who adds this module should do so from day 1, except that in the emulator, the guild table will start from day 3 or 4, and in this way, the ids are reserved for this module. Otherwise, if the module is added after a while, we could delete an already existing guild. However, this information can be added to the README, so that people keep in mind that they must create brotherhoods.
